name: 'Rust Android Build Libs'
description: 'Setup Android NDK for native libs generation from the RUST code'
author: 'Ravinder Jangra'
inputs:
  api:
    description: 'Android API'
    default: '21'
    required: true
  arch:
    description: 'Platform arch'
    required: true
  install-location:
    description: 'Path to use for NDK toolchain'
    required: true
  force:
    description: 'Force install toolchain'
    default: 'false'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
