name: 'Rust Android Build Libs'
description: 'Build Android native libs from the RUST code'
author: 'Ravinder Jangra'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
